version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: railway-test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: footballsim
    ports:
      - "5432:5432"
    volumes:
      - railway-test-pgdata:/var/lib/postgresql/data
    networks:
      - railway-test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.railway
    container_name: railway-test-app
    ports:
      - "8080:8080"
    environment:
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: footballsim
      PORT: 8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - railway-test-network

volumes:
  railway-test-pgdata:

networks:
  railway-test-network:
    driver: bridge 