[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile.railway"
watchPatterns = ["./cmd/**/*.go", "./database/**/*.go", "./handlers/**/*.go", "./models/**/*.go", "./services/**/*.go"]

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
healthcheckPath = "/"
healthcheckTimeout = 300

[env]
PORT = "8080" 