services:
  - type: web
    name: football-sim
    env: docker
    plan: free
    buildCommand: docker build -t football-sim .
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: football-sim-db
          property: connectionString

databases:
  - name: football-sim-db
    plan: free
    ipAllowList: [] 